build:
  test:
    image: golang:1.8.1-alpine
    environment:
      ENV: CI
    commands:
      - echo "this is a go app"
    when:
      event:
        - push

cache:
  mount:
    - /drone/.npm
    - /drone/.pip

deploy:
  ##################
  # DEV ENVIRONMENT
  ##################
  gae:
    environment:
      BUILD_NUM: $$COMMIT
      ENV_NAME: 'dev'
    action: update
    image: nytimes/drone-gae
    project: &dev_project sudo-marketing
    app_file: dev.yaml
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_DEV
    ae_environment:
      APP_NAME: gtd-util
      APP_VERSION: "2.0.0"
      ENV_NAME: 'dev'
      MEMCACHE_HOST: google
      SEC_1: $$SEC_1
    when:
      event: push
      branch: master

  gae:
    image: nytimes/drone-gae
    action: set_default_version
    project: sudo-marketing
    app_file: dev.yaml
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS
    when:
      event: push
      branch: feature/ae
