build:
  test:
    image: golang:1.8.1-alpine
    environment:
      ENV: CI
    commands:
      - echo "this is a go app  "
    when:
      event:
        - push

deploy:
  ssh:
    host: 127.0.0.1
    user: root
    port: 22
    commands:
      - echo hello
      - echo world
