build:
  test:
    image: golang:1.8.1-alpine
    environment:
      ENV: CI
    commands:
      - echo "this is a go app  "
    when:
      event:
        - push

publish:
  gcr:
    context: nginx
    debug: true
    file: nginx/Dockerfile
    registry: us.gcr.io
    repo: inspiring-cat-165403/nginx
    tag:
      - latest
      - $$COMMIT
    token: >
      $$GOOGLE_CREDENTIALS
    when:
      event: push

  gcr:
    context: api
    debug: true
    file: api/Dockerfile
    registry: us.gcr.io
    repo: inspiring-cat-165403/api
    tag:
      - latest
      - $$COMMIT
    token: >
      $$GOOGLE_CREDENTIALS
    when:
      event: push
