# NOTE: this file is parsed as a golang template.
---
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: {{.app}}-{{.env}}

spec:
  replicas: {{.replicas}}

  template:
    metadata:
      labels:
        app: {{.app}}
        env: {{.env}}

    spec:
      containers:
        - name: application
          image: {{.image}}
          ports:
            - containerPort: 8000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: {{.app}}-{{.env}}

spec:
  scaleTargetRef:
    kind: Deployment
    name: {{.app}}-{{.env}}
  minReplicas: {{.replicas_min}}
  maxReplicas: {{.replicas_max}}
  targetCPUUtilizationPercentage: {{.cpu}}
---
apiVersion: v1
kind: Service

metadata:
  name: {{.app}}-{{.env}}

spec:
  type: LoadBalancer
  selector:
    app: {{.app}}
    env: {{.env}}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
