web:
  restart: always
  build: ./web
  expose:
    - "8080"
  ports:
    - "8080:8080"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: .env
  # entrypoint: ./web/entry-point.sh
  # command: python -m SimpleHTTPServer
  command: /usr/local/bin/gunicorn -w 2 -b :8080 app:app

# nginx:
#   restart: always
#   build: ./nginx/
#   ports:
#     - "80:80"
#   volumes:
#     - /www/static
#   volumes_from:
#     - web
#   links:
#     - web:web

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5454:5454"
