webpack:
  build: ./watcher-app
  expose:
    - "3000"
  ports:
    - "3000:3000"
  volumes:
    - ./watcher-app/src:/watcher-app/src
    - ./watcher-app/tasks:/watcher-app/tasks
  entrypoint: gulp dev
